Repository zscaler/terraform-provider-zpa, pull requests merged in 2022-10, with the labels that each got.

#188 feat(new parameters):App Connector Group TCPQuick*
  .github/workflows/ci.yml
  .github/workflows/release.yml
  CHANGELOG.md
  version
  zpa/common/testing/variable/variable.go
  zpa/data_source_zpa_app_connector_group.go
  zpa/resource_zpa_app_connector_group.go
  zpa/resource_zpa_app_connector_group_test.go
Labels: new-resource

#193 fix rule order issue when no deception rule exist
  .github/workflows/ci.yml
  go.mod
  go.sum
  zpa/resource_zpa_policy_access_rule.go
Labels: type/bug

#194 Updated to zscaler-sdk-go v0.1.1
  go.mod
  go.sum
Labels: go, needs-zpa-sdk-golang-upgrade

#196 Fix: Rename/Fix Browser Access Application Segment
  CHANGELOG.md
  GNUmakefile
  docs/data-sources/zpa_application_segment_browser_access.md
  docs/guides/release-notes.md
  docs/resources/zpa_application_segment_browser_access.md
  examples/zpa_application_segment_browser_access/basic_v1.tf
  examples/zpa_application_segment_browser_access/basic_v2.tf
  go.mod
  go.sum
  zpa/common/resourcetype/resource_type.go
  zpa/data_source_zpa_application_segment_browser_access.go
  zpa/data_source_zpa_application_segment_browser_access_test.go
  zpa/provider.go
  zpa/resource_zpa_application_segment_browser_access.go
  zpa/resource_zpa_application_segment_browser_access_test.go
Labels: type/bug, type/enhancement

#197 Feat: service_edge_group new validation parameters
  zpa/common.go
  zpa/common/testing/variable/variable.go
  zpa/data_source_zpa_service_edge_group_test.go
  zpa/resource_zpa_service_edge_group.go
  zpa/resource_zpa_service_edge_group_test.go
Labels: type/enhancement

#198 replace depercated ConfigureFunc with ConfigureContextFunc
  go.mod
  zpa/provider.go
Labels: type/enhancement

#199 Zpa #197 task3 fix applicatin segments port conflict
  zpa/resource_zpa_application_segment.go
Labels: type/bug, type/enhancement
