Repository zscaler/terraform-provider-zpa, pull requests merged in 2023-05, with the labels that each got.

#301 improve scim values searching
  CHANGELOG.md
  docs/guides/release-notes.md
  go.mod
  go.sum
  zpa/common.go
Labels: type/enhancement

#304 (Fix) connector_close_to_app to all app segments
  CHANGELOG.md
  GNUmakefile
  docs/guides/release-notes.md
  docs/resources/zpa_application_segment.md
  docs/resources/zpa_application_segment_browser_access.md
  docs/resources/zpa_application_segment_inspection.md
  docs/resources/zpa_application_segment_pra.md
  zpa/resource_zpa_application_segment.go
  zpa/resource_zpa_application_segment_browser_access.go
  zpa/resource_zpa_application_segment_inspection.go
  zpa/resource_zpa_application_segment_pra.go
Labels: type/bug

#306 (fix) Fix policy_forwarding_rule to ensure updates
  CHANGELOG.md
  GNUmakefile
  docs/guides/release-notes.md
  go.mod
  go.sum
  zpa/resource_zpa_policy_access_forwarding_rule.go
Labels: type/bug

#307 (fix) Fix policy_timeout_rule to ensure updates
  CHANGELOG.md
  docs/guides/release-notes.md
  zpa/resource_zpa_policy_access_timeout_rule.go
Labels: type/bug

#310 (Doc) Updated documentation to v 2.7.7
  CHANGELOG.md
  docs/guides/release-notes.md
  docs/index.md
Labels: documentation

#312 (Fix) Fix ZPA Service Edge resource and datasource
  CHANGELOG.md
  GNUmakefile
  docs/guides/release-notes.md
  go.mod
  go.sum
  zpa/data_source_zpa_service_edge.go
  zpa/data_source_zpa_service_edge_group.go
  zpa/resource_zpa_segment_group.go
  zpa/resource_zpa_service_edge_group.go
Labels: type/bug
