Repository zscaler/terraform-provider-zpa, pull requests merged in 2023-01, with the labels that each got.

#232 Added New ZPA Inspection Control Parameters
  CHANGELOG.md
  GNUmakefile
  docs/data-sources/zpa_inspection_all_predefined_controls.md
  docs/data-sources/zpa_inspection_custom_control.md
  docs/data-sources/zpa_inspection_predefined_controls.md
  docs/data-sources/zpa_inspection_profile.md
  docs/resources/zpa_inspection_custom_control.md
  docs/resources/zpa_inspection_profile.md
  go.mod
  go.sum
  zpa/data_source_zpa_inspection_all_predefined_controls.go
  zpa/data_source_zpa_inspection_custom_controls.go
  zpa/data_source_zpa_inspection_custom_controls_test.go
  zpa/data_source_zpa_inspection_predefined_controls.go
  zpa/data_source_zpa_inspection_profile.go
  zpa/data_source_zpa_inspection_profile_test.go
  zpa/resource_zpa_inspection_custom_controls.go
  zpa/resource_zpa_inspection_custom_controls_test.go
  zpa/resource_zpa_inspection_profile.go
  zpa/resource_zpa_inspection_profile_test.go
  zpa/resource_zpa_policy_access_inspection_rule_test.go
Labels: documentation, type/enhancement

#234 fix application segment delete issue
  zpa/resource_zpa_application_segment.go
  zpa/resource_zpa_application_segment_browser_access_test.go
  zpa/resource_zpa_application_segment_inspection_test.go
  zpa/utils.go
Labels: type/bug

#238 feat: Added new LSS log_type attribute
  CHANGELOG.md
  GNUmakefile
  docs/data-sources/zpa_lss_config_log_type_formats.md
  docs/guides/release-notes.md
  docs/resources/zpa_lss_config_controller.md
  zpa/data_source_zpa_lss_config_log_types_formats.go
  zpa/data_source_zpa_lss_config_log_types_formats_test.go
  zpa/resource_zpa_lss_config_controller.go
Labels: type/enhancement
